git:
  depth: false
addons:
  sonarcloud:
    organization: "monarch-initiative"
    token:
      secure: "vFrJpycHuVEqWmsdwhCQgPFEmoxgw+m2/Y4vxCTeqwwOGGMeInuiE46tuN8crhvwrh4i/GHtUKSfokS04/K55Du+y3vW7mDGDgYgDOiShiwI9f5VJWy/5MVHCw/nbTgivQvqsGitZIxygo1gQHU1ush/3QiWfPMNNxDbV6G3WhMe1VrMVBlV5WLSWz/ETAz+SagLpt2MTe2j4XHoPCZRk6ximaUHqzP6TpGDuWFoQBPEUGuGnSnd568YaJfQVUggh+newhLKTVisJH1JOgLVNtJdabWFwRfRihvyZFXdM2j3s+jzrrvHoldepM6+IidEEyGKjDLD2Q9pVJcyvwq6Nl6f6V3ohClZLpdGJG0CudNMqCmrlLZZHtyJQayqXZqTSK5l7H9uoPq6P94NXdxHx3VVKz16uUuMjNhESfUxonZHJTu/vFnaZdtSIuXQp9N7f4uUZFSv+BSMYUY3mAD/uwIy8RlM20JhW6xCu5K6OQJIr5l2B3bLmbyc9QvNd5uHPUl5rc62sRfOuQd80Re4qpgZN5V1I5FEWNaZ+RjxHGp/adkYcsZjK3erihdFEclV9tuVr6zIlR+MtV4bATozePZIWyhPUhxC/h+xj9dl9ejuFS53YnemMoPDfBgUvdQg5c4oAvwNujKtMgbd1/4Y6zxes7oSeE9LU+9uqtelxKU="
  apt:
    packages:
      - libc6
      - gcc
      - binutils-dev

language: python
python:
- '3.7'
before_install:
- pip install pip --upgrade
install:
- pip install .[test]
- pip install cmake
- pip install .[visualization]
- python -m nltk.downloader all
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest tests --cov=embiggen --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- pylint --errors-only --exit-zero embiggen
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs
after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: G+6L9J0/zJOhZTUI2KsVIffqTSNbrFWNKKxeKw/epwutiwMpo/ZOOxBD3xTA9eQCXeIK3qq6YgJZTSVGv+nEbnKjUCeKJnQr2NOHfQ5ke8w4XeTk5C4Wkvwb7V7PVrwkRxWO5b32mvwECzwro07pl1gqZ50M59iyiW9ZK3ofuGoT0dq2j18s1cKvPkUE/HbYS2NPGPHde/Hf+WFcWO7Xx5yAZDcscu1h8/hSR95VXcx6fD9q3gkDv4dE6O/OpUErNFQYLyepgNgM6+iqwTrjotc9Ch/I60KnheQbx6fFoHLiE/gOpGJxZE271hea9SZFrDWq3dzLDW+fKwY+4h/I5wXsYbmmVV/mCeL9iOG70GnSB0lBu6JHqAS17YfDNPdhADuYqj7pzfmm8gh0yDa/ppjIxPNGc7qTa8A1cWhTBmrjkT5A4plfLgA8KG4Vr3EOL5BWAltguBbBusuDySy2bIpaNczyZB79BNoJaJZkMW7lNqtYChTKFe3zIqPn/RLIv3Db5Jt2qxQp3pjCKu6+B2Pwz3FFR6qvA7SBC5y3wAL7MTSzcE5oA3ZuKRHqhMeJbdFFPsuJnuOwQ2J3bDxay9nAt23F9fQEzU58vePtq4Mja3ufqh2go2O9LTurDUMiLSiB8Wc0t8f7DR0D/zCTUY9yR4CO25MQlYVPfi/eBaE=
  - secure: kgACYjxEt6gDh8s22KjG/Dq/u2uBCrGqmgrIZbzEH38KlAu5OeCo/g4HasyDEyCFohQhy0HHIkcT/fkJ1pUPZmZscJs8l2QMyIUHrAjgpucdClwUQ2U/Fcz0SNmCGMkGuw/I/WmIiNL2qxapYc91UDzOzA7NBhahQSG+niYKuHfrMo4TNqZlYKJ5wbnf8/c7XipcYBxkT+/KKhJVqIEDSD0iFoOIR8zRPdkdD2J8S/vMUHHxyKRToy0qh67kM80ygNTxSpznWcTLJ8We5DCmXZ+oEJq9pRiYQLLzt6c7McLt/A7G2aR1seGvJU4AXChMLmzY711PwMvQk4psAuk9t/ungKQ395lRLw/Y7+2uz05Zn7/2DWcHZWPR18u01EUinZowf9pJsy6ccZZhTd4tpW1e9ihJ4fBckv9cxmcJhXIbuFWY8frkr8ZOi2a5yQV2WOq9vrFpUYXoGN7swUCGAMJp1nuaxgBmm3rueTPaso4R3P5WOns6zZJR4lqLsZDUnVetseZmBmQ89Wm7dWD3DRq7T7iLGfjJcVVF2GiqLghpF6Y/YXITdDcoIwzD/2XffnaAsMpE4bqPRxN/H2lLvPtfDwIGs/7HXQWKhh9uiOxLR3qh7fW2SPhWZfGBzu0P4GU3vKXxvQOMmfgoZA6oQYPdzNF98jX+pWb/uOE8A2Y=
